steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['clean', 'install']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuild', '.']
  - name: gcr.io/cloud-builders/docker
    args: [ 'push', 'gcr.io/$PROJECT_ID/cloudbuild']
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=k8s-deployment.yaml
      - --image=gcr.io/$PROJECT_ID/cloudbuild:latest
      - --location=us-central1-c
      - --cluster=cluster-dev