steps:
  - name: maven:3-jdk-8
    id: "Test"
    entrypoint: mvn
    args: ['clean', 'install']
  - name: gcr.io/cloud-builders/docker
    id: "Build"
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuild:$SHORT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    id: "Push"
    args: ['push', 'gcr.io/$PROJECT_ID/cloudbuild:$SHORT_SHA']
  - name: gcr.io/cloud-builders/gke-deploy
    id: "Deploy"
    args:
      - run
      - --filename=k8s-deployment.yaml
      - --image=gcr.io/$PROJECT_ID/cloudbuild:$SHORT_SHA
      - --location=us-central1-c
      - --cluster=cluster-dev