apiVersion: "v1"
kind: "Service"
metadata:
  name: "cloudbuild-service"
  namespace: "default"
  labels:
    app: "cloudbuild"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
  selector:
    app: "cloudbuild"
  type: "LoadBalancer"