apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cloudbuild
  namespace: default
  labels:
    app:  cloudbuild
spec:
  selector:
    matchLabels:
      app: cloudbuild
      version: latest
  replicas: 2
  template:
    metadata:
      labels:
        app:  cloudbuild
    spec:
      containers:
        - name:  cloudbuild
          image: gcr.io/crm-dev-288219/cloudbuild:latest
          ports:
          - containerPort: 8080
